// Generated by LiveScript 1.6.0
(function(){
  browser.runtime.onInstalled.addListener(function(){
    var xhr;
    xhr = new XMLHttpRequest();
    xhr.open('GET', 'https://www.google.com.tw');
    xhr.onload = function(){
      if (xhr.status === 200) {
        console.log("get something from google");
        console.log(xhr);
      } else {
        console.log("fail ajax");
      }
    };
    xhr.send();
  });
}).call(this);
